[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "frontend/netlify/functions"
  included_files = ["!**/fcm-send.js"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Configuration des Edge Functions pour injecter le script de correction
[[edge_functions]]
  path = "/*"
  function = "transform"

[dev]
  framework = "vite"
  targetPort = 5173
