[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

[dev]
  framework = "vite"
  command = "cd frontend && npm run dev"
  port = 8888
  targetPort = 5173
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"
  functionsPort = 9999

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "frontend/netlify/functions"
  node_bundler = "esbuild"
  included_files = ["!**/fcm-send.js"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Configuration des Edge Functions pour injecter le script de correction
[[edge_functions]]
  path = "/*"
  function = "transform"

[build.environment]
  NODE_VERSION = "20"
  # Environment variables should be configured in the Netlify dashboard
  # Do not define variables here as they are not properly substituted
